[project]
name = "recetas-app"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "ksotela56-sketch", email = "ksotela56@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
recetas-app = "recetas_app:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
